---
title: "Quiz 1"
author: "PSTAT 120B"
date: "Spring 2023"
output: pdf_document
header-includes:
    - \usepackage{geometry}
    - \usepackage{fancyhdr}
    - \usepackage{url}
    - \usepackage{booktabs}
    - \usepackage{hyperref}
    - \usepackage{color}
    - \usepackage{lastpage}
    - \usepackage{multirow}
    - \usepackage{graphicx}
    - \usepackage{lscape}
    - \usepackage{float}
#    - \usepackage{draftwatermark}
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE)
```

\pagestyle{fancy}
\lhead{Spring 2023}
\chead{}
\rhead{Quiz 1}
\lfoot{}
\cfoot{\small \thepage}
\rfoot{}

\section*{Instructions:}

\textsc{Write clearly} and neatly on a sheet of paper. Make sure to write your full name, as listed on GauchoSpace, and your perm number at the top of the page in order to receive credit. You should \textbf{try not to} use your notes to complete this quiz; we encourage you to attempt it without assistance in order to check your understanding of the material.

\section*{Rubric:}

Assign yourself a score from 0 to 4 and clearly indicate that score at the top of the page. If you got no parts correct, you earned a zero -- one, a one, and so on.

\section*{Problem:}

\begin{enumerate}

\item Let $X \sim U(5, 10)$ and $Y \sim U(5, 10)$ be independent random variables. Let $c = 2$, $d = 3.5$, and $e = 6$. For (b), (c), and (d) below, you should find and report a specific number.

Note that the density of a uniform random variable $U(a, b)$ is $\frac{1}{b-a}$.

\begin{enumerate}

\item Write the joint density $f(x, y)$.

$$
\begin{aligned}
f(x, y) &= f(x)f(y) \\
&= \left(\frac{1}{10-5}\right)\left(\frac{1}{10-5}\right) \\
f(x, y) &= 0.04
\end{aligned}
$$

\item Find $E[cdX - Y + e]$.

Note: You can use any means of finding $E[X]$, including deriving it directly or remembering/reasoning about it.

$$
\begin{aligned}
E[cdX - Y + e] &= E[cdX] - E[Y] + E[e] \\
&= cdE[X] - E[Y] + e \\
&= 2(3.5)(7.5) - 7.5 + 6 \\
E[cdX - Y + e] &= 51
\end{aligned}
$$

\item Find $E[Y^{2}]$.

You should remember to use the variance identity from the homework problem(s); that tells us that $E[Y^2] = E[Y]^2 + Var(Y)$. Then we know that the variance of a uniform is $\frac{(b - a)^2}{12} = \frac{25}{12} = 2.083333$.

So $E[Y^2] = 7.5^2 + 2.083333$, or $E[Y^2] = 58.33$.

\item Find $var(cX + dY + e)$.

We know from the homework that $var(cX + dY + e) = c^{2}var(X) + d^{2}var(Y) + 2cdcov(X, Y)$. Because $X$ and $Y$ are independent, we also know from the homework that $cov(X, Y) = 0$. So:

$$
\begin{aligned}
var(cX + dY + e) &= c^2var(X) + d^2var(Y) \\
&= 2^2(2.083333) + 3.5^2(2.083333) \\
&= 33.85416
\end{aligned}
$$

\end{enumerate}
\end{enumerate}