---
title: "Introduction to Statistical Machine Learning"
author: "PSTAT 131/231"
date: "Spring 2022"
output: pdf_document
header-includes:
    - \usepackage{geometry}
    - \usepackage{fancyhdr}
    - \usepackage{url}
    - \usepackage{booktabs}
    - \usepackage{hyperref}
    - \usepackage{color}
    - \usepackage{lastpage}
    - \usepackage{multirow}
    - \usepackage{graphicx}
    - \usepackage{lscape}
#    - \usepackage{draftwatermark}
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- \documentclass[11pt]{article} -->
<!-- \usepackage[left=1in,top=1in,right=1in,bottom=1in,headheight=14pt]{geometry} -->
<!-- \usepackage{fancyhdr} -->
<!-- \usepackage{url} -->
<!-- \usepackage{booktabs} -->
<!-- \usepackage{hyperref} -->
<!-- \usepackage{color} -->
<!-- \usepackage{lastpage} -->
<!-- \usepackage{multirow} -->
<!-- \usepackage{graphicx} -->
<!-- \usepackage{lscape} -->
<!-- \hypersetup{colorlinks=true, urlcolor=blue} -->

<!-- \title{Introduction to Statistical Machine Learning} -->
<!-- \author{PSTAT 131/231} -->
<!-- \date{Winter 2022} -->

\pagestyle{fancy}
\lhead{Spring 2022}
\chead{}
\rhead{131/231 Syllabus}
\lfoot{}
\cfoot{\small \thepage}
\rfoot{}

<!-- \begin{document} -->
<!-- \maketitle -->
\begin{center}
\begin{tabular}{ll}
\textsc{Instructor:} &Dr. Katie Coburn (\href{mailto:katie\_m\_coburn@ucsb.edu}{\texttt{katie\_m\_coburn@ucsb.edu}}) \\
\textsc{Teaching Assistants:} &Hanmo Li (\href{mailto:hanmo@pstat.ucsb.edu}{\texttt{hanmo@pstat.ucsb.edu}})\\
    &Lihao Xiao (\href{mailto:lihao@pstat.ucsb.edu}{\texttt{lihao@pstat.ucsb.edu}}) \\
    %&Minwoo Park (\href{mailto:minwoo@pstat.ucsb.edu}{\texttt{minwoo@pstat.ucsb.edu}}) \\
\textsc{Lecture:} &MW 5:00 - 6:15 pm Embarcadero Hall or \\ &Zoom \href{https://ucsb.zoom.us/j/6425299662}{https://ucsb.zoom.us/j/6425299662} \\
\textsc{Sections:}
&T 10:00 - 10:50 am SSMS 1303 \textsc{Xiao} \\
&T 4:00 - 4:50 pm SSMS 1302 \textsc{Xiao} \\
&T 5:00 - 5:50 pm SSMS 1302 \textsc{Li}\\
&T 6:00 - 6:50 pm SSMS 1302 \textsc{Li}\\
\end{tabular}
\end{center}

\section*{Course information}

\subsection*{Description}
\textsc{Statistical} machine learning is used to discover patterns and relationships in large data sets. Topics will include: data exploration, classification and regression tress, random forests, clustering and association rules. Building predictive models focusing on model selection, model comparison and performance evaluation. Emphasis will be on concepts, methods and data analysis; and students are expected to complete a significant class project using real-world data. Prerequisites: PSTAT 120A-B and PSTAT 126 with a minimum grade of C or better. Credit units: 4.

\vskip6pt\noindent \textsc{This course} is taught at two levels, one aimed at undergraduates (131 level) and one at graduate students (231 level). Lectures are given at a level designed to be accessible and relevant to all students in the course. Students taking the course at the 231 level will be assigned additional homework questions and are expected to do reading in \textbf{both} the 131 and 231-level textbooks, listed below.

\subsection*{Learning Outcomes}
Upon completion of this course, students should be able to:
\begin{enumerate}
    \item \textsc{Explain} the common statistical learning techniques conceptually and characterize some of
them mathematically;
    \item \textsc{Describe and discuss} the pros and cons of the common statistical learning methods;
    \item \textsc{Use R}, the \textit{tidyverse}, and \textit{tidymodels} effectively for exploratory data analysis, model fitting, and visualization.
\end{enumerate}

\subsection*{Piazza}
\textsc{The course} Piazza page can be found here: \href{https://piazza.com/ucsb/winter2022/pstat131231}{https://piazza.com/ucsb/winter2022/pstat131231}. Sign up with your UCSB school email and with access code \textbf{3435}.

\subsection*{Format}
<!-- \textsc{The first two weeks} of the course are online only. Lectures will be synchronous over Zoom (at the address above). Any lecture slides will be posted on GauchoSpace before class. All \textbf{lectures will be recorded} and uploaded. -->

\textsc{As per the} Spring Quarter Instruction message from the Office of the Executive Vice Chancellor, dual-mode instruction -- defined as livestreaming or classroom recording -- \textbf{cannot} be provided for courses. With this in mind, lectures will be provided in person \textbf{only}. Any lecture slides will be posted on GauchoSpace before the corresponding class. If special circumstances require it, specific lectures may be recorded and shared, but this is an exception.

<!-- \vskip6pt\noindent If/when classes are held in person, every class will be \textbf{simultaneously} streamed live on Zoom (at the address above), so that students can either attend remotely or physically in person. The stream \textbf{will be recorded} and uploaded. This is offered so that students who cannot physically attend \textbf{for any reason} have the option to attend class virtually without penalty. -->

\vskip6pt\noindent The class will progress according to a weekly schedule (provided below) and interact outside of the classroom via Piazza. Students are strongly encouraged to interact on Piazza. The instructional team will monitor Piazza regularly. Piazza should be used for all discussion related to course content, homework, R coding, etc.

\vskip6pt\noindent Both lecture periods each week will consist of slides that cover related concepts, sometimes including live coding to demonstrate how to apply the concepts using the R language. Section each week will be dedicated to completing an R-based lab.

<!-- \newpage -->
\subsection*{Materials}
\textsc{The books} and software used for this class are as follows. Note that all are freely available online and do not require purchase.

\begin{itemize}
    \item \textbf{Required for PSTAT 131 students}: \textit{An Introduction to Statistical Learning with Applications in R} (or ISLR), by G. James, D. Witten, T. Hastie, R. Tibshirani. Available: \href{https://www.statlearning.com/}{https://www.statlearning.com/}
    \item \textbf{Required for PSTAT 231 students}: \textit{The Elements of Statistical Learning: Data Mining, Inference, and Prediction} (or ESL), by T. Hastie, R. Tibshirani, J. Friedman. Available: \href{https://hastie.su.domains/ElemStatLearn/}{https://hastie.su.domains/ElemStatLearn/}
    \item \textbf{Required for all}: \begin{itemize}
        \item The R statistical environment version 4.1.2, available here: \href{https://www.r-project.org/}{https://www.r-project.org/}
        \item \textit{R for Data Science}, by H. Wickham, G. Grolemund. Available: \href{https://r4ds.had.co.nz/index.html}{https://r4ds.had.co.nz/index.html}
        \item The RStudio IDE (integrated development environment) Desktop version. Available: \href{https://www.rstudio.com/products/rstudio/download/#download}{https://www.rstudio.com/} 
    \end{itemize}
\end{itemize}

<!-- \newpage -->
\subsection*{Assessments}
\textsc{Your attainment} of course learning outcomes will be measured by the following assessments, with the relative weighting indicated in parentheses. All assignments within each category are given equal weight.

\vskip6pt\noindent Collaboration and open science are fundamental aspects of data science. You can (and are encouraged) to use the Internet, StackOverflow, etc. as a resource when coding. However, you \textbf{should not} directly copy code or answers. Your code should be well documented; include comments describing each line. If you use a source for help coding, you \textbf{must} cite it.

\vskip6pt\noindent You will \textbf{not} be graded on your completion of lab work or your attendance of labs, but doing the labs is likely to be greatly beneficial for your homework and final project grades. You are strongly encouraged to attend lab sections and follow along with the materials for each lab, which will be posted each week.

\begin{itemize}
\item \textbf{Homework} (50\%). Homework is assigned \textbf{every week} and is due by Sundays at 11:59 PM PDT.  Each homework is worth 50 points.  One homework is assigned each week, except for the last week, for a total of \textbf{nine} homework assignments. Your \textbf{lowest} homework score will be dropped.

\item \textbf{Final Project} (50\%). The final project is a significant portion of the class and allows students to demonstrate their understanding of the material by working with a data set of their own choosing. Each student should begin thinking about their project and looking for a data set immediately; a page on GauchoSpace provides a list of possible resources. You'll receive a lot of guidance about the project over the course of the quarter.

\vskip6pt\noindent The project will require a large amount of work and cannot be satisfactorily completed in only a day (or even a week). You are \textbf{strongly advised} to work on it in stages throughout the quarter. See GauchoSpace for more detailed information and a rubric.
\end{itemize}

\subsection*{Tentative Schedule}
\textsc{The tentative} weekly schedule is indicated below. The topics and reading are subject to change based on the progress of the class.

<!-- % Please add the following required packages to your document preamble: -->
<!-- % \usepackage{booktabs} -->
<!-- % \usepackage{multirow} -->
<!-- % \usepackage{graphicx} -->
<!-- % \usepackage{lscape} -->
\begin{landscape}
\begin{table}[]
\centering
\resizebox{\textwidth}{!}{%
\begin{tabular}{@{}lllllllc@{}}
\toprule
\textbf{Week}                                        & \textbf{Date} & \textbf{Topic}                                                         & \textbf{131 Reading}                                          & \textbf{231 Reading}                                                            & \textbf{Section}        & \textbf{Assignments} & \multicolumn{1}{l}{\textbf{Final Project Stage}}                                                                           \\ \midrule
\multicolumn{1}{c}{\multirow{2}{*}{\textbf{Week 1}}} & Jan. 3        & \begin{tabular}[c]{@{}l@{}}Introduction \&\\ basics of ML\end{tabular} & Ch. 1 ISLR                                                    & Ch. 1 ESL                                                                       & \multirow{2}{*}{Lab 1}  &                      & \multirow{2}{*}{Find a partner}                                                                                            \\
\multicolumn{1}{c}{}                                 & Jan. 5        & Bias-variance tradeoff (I)                                             & \multirow{2}{*}{Ch. 2 ISLR}                                   & \multirow{2}{*}{Ch. 2 ESL}                                                      &                         &                      &                                                                                                                            \\
\multirow{2}{*}{\textbf{Week 2}}                     & Jan. 10       & Bias-variance tradeoff (II)                                            &                                                               &                                                                                 & \multirow{2}{*}{Lab 2}  &                      & \multirow{4}{*}{\begin{tabular}[c]{@{}c@{}}Decide on topic\\ and locate data \\ set(s)\end{tabular}}                       \\
                                                     & Jan. 12       & Linear regression (I)                                                  & Ch. 3 ISLR                                                    & Ch. 3 ESL                                                                       &                         & Homework 1 Due       &                                                                                                                            \\
\multicolumn{1}{c}{\multirow{2}{*}{\textbf{Week 3}}} & Jan.17        & \textbf{NO CLASS MEETING}                                              & \multicolumn{2}{c}{\textbf{HOLIDAY}}                                                                                                            & \multirow{2}{*}{Lab 3}  &                      &                                                                                                                            \\
\multicolumn{1}{c}{}                                 & Jan. 19       & Linear regression (II)                                                 & Ch. 3 ISLR                                                    & Ch. 3 ESL                                                                       &                         & Quiz 1               &                                                                                                                            \\
\multirow{2}{*}{\textbf{Week 4}}                     & Jan. 24       & Logistic regression                                                    & Ch. 4 - 4.3 ISLR                                              & Ch. 4.4 ESL                                                                     & \multirow{2}{*}{Lab 4}  &                      & \multirow{4}{*}{\begin{tabular}[c]{@{}c@{}}Load and tidy data\\ \\ Run and write up\\ descriptive\\ analyses\end{tabular}} \\
                                                     & Jan. 26       & Discriminant analysis                                                  & \begin{tabular}[c]{@{}l@{}}Rest of Ch. 4 \\ ISLR\end{tabular} & \begin{tabular}[c]{@{}l@{}}Rest of Ch. 4 \\ ESL\end{tabular}                    &                         & Homework 2 Due       &                                                                                                                            \\
\multirow{2}{*}{\textbf{Week 5}}                     & Jan. 31       & Resampling methods                                                     & Ch. 5 ISLR                                                    & Ch. 7 ESL                                                                       & \multirow{2}{*}{Lab 5}  & Quiz 2               &                                                                                                                            \\
                                                     & Feb. 2        & Linear model selection                                                 & Ch. 6 - 6.3 ISLR                                              & Ch. 6 ISLR                                                                      &                         &                      &                                                                                                                            \\
\multirow{2}{*}{\textbf{Week 6}}                     & Feb. 7        & Regularization                                                         & Ch. 6.4 - 6.5 ISLR                                            & Ch. 5 ESL                                                                       & \multirow{2}{*}{Lab 6}  &                      & \multirow{8}{*}{\begin{tabular}[c]{@{}c@{}}Run models\\ \\ Write up results\\ \\ Work on draft \\ of paper\end{tabular}}   \\
                                                     & Feb. 9        & Beyond linearity                                                       & Ch. 7 ISLR                                                    & \begin{tabular}[c]{@{}l@{}}Ch. 9.1,\\ 9.3 - 9.4 ESL\end{tabular}                &                         & Homework 3 Due       &                                                                                                                            \\
\multirow{2}{*}{\textbf{Week 7}}                     & Feb. 14       & Decision trees                                                         & Ch. 8.1 ISLR                                                  & Ch. 9.2 ESL                                                                     & \multirow{2}{*}{Lab 7}  & Quiz 3               &                                                                                                                            \\
                                                     & Feb. 16       & Tree-based methods                                                     & \begin{tabular}[c]{@{}l@{}}Ch. 8.2 - 8.3\\ ISLR\end{tabular}  & Ch. 10 ESL                                                                      &                         &                      &                                                                                                                            \\
\multirow{2}{*}{\textbf{Week 8}}                     & Feb. 21       & K-means                                                                & \multirow{2}{*}{Ch. 12.4 ISLR}                                & \multirow{2}{*}{\begin{tabular}[c]{@{}l@{}}Ch. 14.1 - \\ 14.3 ESL\end{tabular}} & \multirow{2}{*}{Lab 8}  &                      &                                                                                                                            \\
                                                     & Feb. 23       & Hierarchical clustering                                                &                                                               &                                                                                 &                         & Homework 4 Due       &                                                                                                                            \\
\multirow{2}{*}{\textbf{Week 9}}                     & Feb. 28       & PCA                                                                    & Ch. 12.2 ISLR                                                 & \begin{tabular}[c]{@{}l@{}}Ch. 14.5 \& \\ 18.6 ESL\end{tabular}                 & \multirow{2}{*}{Lab 9}  & Quiz 4               &                                                                                                                            \\
                                                     & Mar. 2        & SVM (I)                                                                & \multirow{2}{*}{Ch. 9 ISLR}                                   & \multirow{2}{*}{Ch. 12 ESL}                                                     &                         &                      &                                                                                                                            \\
\multirow{2}{*}{\textbf{Week 10}}                    & Mar. 7        & SVM (II)                                                               &                                                               &                                                                                 & \multirow{2}{*}{Lab 10} &                      & \multirow{2}{*}{\begin{tabular}[c]{@{}c@{}}Make edits\\ \\ Begin final draft\end{tabular}}                                 \\
                                                     & Mar. 9        & Neural networks                                                        & Ch. 10 ISLR                                                   & Ch. 11 ESL                                                                      &                         &                      &                                                                                                                            \\ \bottomrule
\end{tabular}%
}
\end{table}
\end{landscape}

\subsection*{Time Commitment}
\textsc{The course} is 4 credit units; each credit unit corresponds to an approximate time commitment of 3 hours. You should expect to allocate 12 hours per week to the course. If you find yourself spending considerably more time on the course on a regular basis, please let the instructor or TAs know so that we can help you balance the workload.

\noindent A suggested allocation of this time is as follows: 
\begin{itemize}
    \item Reading and class time: 3 hours (25\%)
    \item Homework: 4.5 hours (37.5\%)
    \item Sections: 1 hour (8.3\%)
    \item Final project: 4.5 hours (37.5\%)
\end{itemize}

<!-- %\newpage -->
\section*{Course Policies}

\subsection*{Communication}
\textsc{There are five} means of communication with other students or the instructional team: during/after class, Piazza, office hours, email, and individual appointments. \textbf{Please use them in that order}. \begin{enumerate}

    \item \textbf{During/after class}. The easiest way to get in touch with me is to walk up after class (if meeting in person) or message me in Zoom chat during/after class (if meeting online). 
    \item \textbf{Piazza}. Consider Piazza your primary communication resource for the course; it is a way to stay connected with the instructor, the TAs, and your classmates throughout the term. You can start and participate in conversations, ask and answer questions, create discussions for specific purposes as you see fit (\textit{e.g.}, forming a study group), and exchange direct messages with anyone in the class. 
    
    \item \textbf{Office hours}. Office hours are offered at a minimum of twice weekly. One session will be conducted by the instructor, the other(s) by various combinations of TAs. These are opportunities to interact informally, ask questions, and discuss course material or assignments.
    
    \item \textbf{Email}. Please use email with discernment for simple communication. A response is guaranteed within 48 weekday hours (so if you email on Friday afternoon, you may not receive a reply until Tuesday afternoon). In light of this response policy, bear in mind that you are likely to receive replies to messages or posts in Piazza much faster than replies to email. If your message is time-sensitive, please indicate so in the subject, and we will do our best to respond promptly.
    
    \begin{itemize}
        \item Note: I am notoriously slow at replying to email -- if the matter is urgent you might need to email me multiple times, or catch me in person/at office hours. Don't feel bad about doing this and please be assured there is never anything personal about a delayed reply.
    \end{itemize}
    
    \item \textbf{Appointment}. You can schedule 20-minute appointments with me as needed. These appointments may be either on Zoom or in person. This mode of communication is best suited to more complex or nuanced communication regarding personal matters. If you schedule an appointment, you will be prompted to indicate what you wish to discuss. 
\end{enumerate}

\subsection*{Extra Credit} 
\textsc{If the class} reaches a 90\% submission rate of ESCI surveys at the end of the quarter, the \textbf{entire class} will receive 2 free points on the final project.

<!-- %\newpage -->
\subsection*{Grades} 
\textsc{Your overall grade} in the course will be calculated as the weighted average of the proportions of total possible points in each assessment category according to the weightings indicated in the Assessments section and reported as a percentage rounded to two decimal places. Tentatively, letter grades will be assigned according to the rubric below -- a curve is possible, but not guaranteed.

\begin{center}
\begin{tabular}{lr}
    A &93\% -- 100.00\%  \\
    A- &90\% -- 92.99\% \\
    B+ &87\% -- 89.99\% \\
    B &83\% -- 86.99\% \\
    B- &80\% -- 82.99\% \\
    C+ &77\% -- 79.99\% \\
    C &73\% -- 76.99\% \\
    C- &70\% -- 72.99\% \\
    D+ &67\% -- 69.99\% \\
    D &60\% -- 66.99\% \\
    F &0\% -- 59.99\%
\end{tabular}
\end{center}

\noindent \textsc{You can} keep track of your marks on individual assessments, your marks in each assessment category, and your overall grade in the GauchoSpace gradebook. Please notify the instructor or TAs of any errors in grade \textit{entry}; please do not attempt to negotiate the grades themselves. If at the end of the course you believe your grade was unfairly assigned, you are entitled to contest it according to the procedure outlined \href{https://my.sa.ucsb.edu/catalog/Current/AcademicPoliciesProcedures/ContestedGrades.aspx}{here} in the UCSB General Catalog.


\subsection*{Deadlines} 
\textsc{You receive} two free late homework submissions without penalty. This policy applies only to homeworks. There is no need to notify the instructor or TAs to use these late allowances; simply submit within one week of the original deadline.

\vskip6pt\noindent \textsc{Non-exempted} homeworks turned in within one week of the deadline will be awarded 50\% credit. No credit will be awarded for homework turned in more than one week late; please plan ahead and submit your work on time.

\vskip6pt\noindent \textsc{The final project} deadline is firm and no late submissions will be accepted.

\subsection*{Extensions} 
\textsc{Extensions} may be granted based on individual circumstances at the instructor's discretion.

\subsection*{Conduct} 
\textsc{Please be mindful} of maintaining respectful and kind communication.  You are expected to uphold the UCSB student code of conduct in your behavior when in class, in section, or interacting with other students or the instructional team. You can find the student code of conduct on the Office of Student Conduct website from \href{http://studentconduct.sa.ucsb.edu/policies-procedures}{this page}. If you are uncomfortable with the conduct of another individual for any reason, please notify the instructor or TAs.

\subsection*{Academic Integrity} 
\textsc{Please maintain integrity} in learning. Your work in the course must be your own. Any form of plagiarism, cheating, misrepresentation of individual effort on assignments and assessments, falsification of information or documents, or misuse of course materials compromises your own learning experience, that of your peers, and undermines the integrity of the UCSB community. Any evidence of dishonest conduct will be discussed with the student(s) involved and reported to the Office of Student Conduct. If you are reading this, thank you for paying close attention to the syllabus. Make an instructor-only post on Piazza with the code word ``integrity.'' Depending on the nature of the evidence and the violation, penalty in the course may range from loss of credit to automatic failure. For a definition and examples of dishonesty, a discussion of what constitutes an appropriate response from faculty, and an explanation of the reporting and investigation process, see the \href{https://studentconduct.sa.ucsb.edu/academic-integrity}{OSC page on academic integrity}. 

\subsection*{Accommodations} 
\textsc{Reasonable accommodations} will be made for any student with a qualifying disability. Such requests should be made through the Disabled Students Program (DSP). More information, instructions on how to access accommodations, and information on related resources can be found on \href{https://dsp.sa.ucsb.edu/}{DSP website}. Remote learning may present unique accommodation needs requiring additional flexibility; students receiving accommodation via DSP are invited to discuss this with the instructor if desired.

\subsection*{Student Evaluations} 
\textsc{Toward the end} of the term, you will be given an opportunity to provide feedback about the course. Your suggestions and assessments are essential to improving the course, so please take the time to fill out the evaluations thoughtfully. 

\subsection*{Student Resources}
\textsc{Any students} in need are encouraged to make use of the following resources.

\begin{itemize}
    \item Financial Crisis Response Team \\ 
    \href{https://food.ucsb.edu/about/committees/financial-crisis-response-team}{https://food.ucsb.edu/about/committees/financial-crisis-response-team}
    \item Food Security and Basic Needs (Food, Housing, Technology) Advising Center \\
    \href{https://food.ucsb.edu/resources/basic-needs-advocates}{https://food.ucsb.edu/resources/basic-needs-advocates}
    \item Undocumented Student Services \\
    \href{http://www.sa.ucsb.edu/dreamscholars/home}{http://www.sa.ucsb.edu/dreamscholars/home}
    \item Campus Advocacy, Resources, and Education (CARE) \\
    \href{https://care.ucsb.edu/}{https://care.ucsb.edu/} \\
    24/7 Confidential Phone: (805) 893-4613
    \item The Trevor Project \\  \href{https://www.thetrevorproject.org/}{https://www.thetrevorproject.org/}
    \item Counseling and Psychological Services (CAPS) \\ 
    \href{https://caps.sa.ucsb.edu/}{https://caps.sa.ucsb.edu/} \\
    24/7 Counselors: (805) 893-4411, press 2
\end{itemize}
