---
title: "Introduction to Statistical Machine Learning"
author: "PSTAT 131/231"
date: "Winter 2023"
output: pdf_document
header-includes:
    - \usepackage{geometry}
    - \usepackage{fancyhdr}
    - \usepackage{url}
    - \usepackage{booktabs}
    - \usepackage{hyperref}
    - \usepackage{color}
    - \usepackage{lastpage}
    - \usepackage{multirow}
    - \usepackage{graphicx}
    - \usepackage{lscape}
    - \usepackage{float}
#    - \usepackage{draftwatermark}
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- \documentclass[11pt]{article} -->
<!-- \usepackage[left=1in,top=1in,right=1in,bottom=1in,headheight=14pt]{geometry} -->
<!-- \usepackage{fancyhdr} -->
<!-- \usepackage{url} -->
<!-- \usepackage{booktabs} -->
<!-- \usepackage{hyperref} -->
<!-- \usepackage{color} -->
<!-- \usepackage{lastpage} -->
<!-- \usepackage{multirow} -->
<!-- \usepackage{graphicx} -->
<!-- \usepackage{lscape} -->
<!-- \hypersetup{colorlinks=true, urlcolor=blue} -->

<!-- \title{Introduction to Statistical Machine Learning} -->
<!-- \author{PSTAT 131/231} -->
<!-- \date{Winter 2022} -->

\pagestyle{fancy}
\lhead{Winter 2023}
\chead{}
\rhead{131/231 Syllabus}
\lfoot{}
\cfoot{\small \thepage}
\rfoot{}

<!-- \begin{document} -->
<!-- \maketitle -->
\begin{center}
\begin{tabular}{ll}
\textsc{Instructor:} &Dr. Katie Coburn (\href{mailto:katie\_m\_coburn@ucsb.edu}{\texttt{katie\_m\_coburn@ucsb.edu}}) \\
\textsc{Teaching Assistants:} &Mingzhao Hu (\href{mailto:mingzhaohu@ucsb.edu}{\texttt{mingzhaohu@ucsb.edu}})\\
    &Huiyu Jiang (\href{mailto:huiyujiang@ucsb.edu}{\texttt{huiyujiang@ucsb.edu}}) \\
    &Kuai Yu (\href{mailto:kuaiyu@ucsb.edu}{\texttt{kuaiyu@ucsb.edu}}) \\
    &Alvin Liu (\href{mailto:ziyueliu@ucsb.edu}{\texttt{ziyueliu@ucsb.edu}}) \\
    &John O'Brien (\href{mailto:johnobrien@ucsb.edu}{\texttt{johnobrien@ucsb.edu}}) \\
\textsc{Undergraduate Learning Assistants:} &Ryan Stofer (\href{mailto:rstofer@ucsb.edu}{\texttt{rstofer@ucsb.edu}}) \\
&Allen Wang (\href{mailto:xin874@ucsb.edu}{\texttt{xin874@ucsb.edu}}) \\
\textsc{Lectures:} &TR 2:00 - 3:15 pm Buchanan 1920 \\
&TR 5:00 - 6:15 pm North Hall 1006
\end{tabular}
\end{center}

\section*{Course information}

\subsection*{Description}
\textsc{Statistical} machine learning is used to discover patterns and relationships in large data sets. Topics will include: data exploration, classification and regression tress, random forests, clustering and association rules. Building predictive models focusing on model selection, model comparison and performance evaluation. Emphasis will be on concepts, methods and data analysis; and students are expected to complete a significant class project using real-world data. Prerequisites: PSTAT 120A-B and PSTAT 126 with a minimum grade of C or better. Credit units: 4.

\vskip6pt\noindent \textsc{This course} is taught at two levels, one aimed at undergraduates (131 level) and one at graduate students (231 level). Lectures are given at a level designed to be accessible and relevant to all students in the course. Students taking the course at the 231 level will be assigned \textbf{additional homework questions} and must do the reading in \textbf{both} the 131 and 231-level textbooks, listed below. The final project assignment is the same for both levels.

\subsection*{Learning Outcomes}
Upon completion of this course, students should be able to:
\begin{enumerate}
    \item \textsc{Explain} the common statistical learning techniques conceptually and characterize some of
them mathematically;
    \item \textsc{Describe and discuss} the pros and cons of the common statistical learning methods;
    \item \textsc{Use R}, the \textit{tidyverse}, and \textit{tidymodels} effectively for exploratory data analysis, model fitting, and visualization.
\end{enumerate}

\subsection*{Format}
<!-- \textsc{The first two weeks} of the course are online only. Lectures will be synchronous over Zoom (at the address above). Any lecture slides will be posted on GauchoSpace before class. All \textbf{lectures will be recorded} and uploaded. -->

\textsc{Lectures} will be provided \textbf{in person only}. Any lecture slides will be posted on GauchoSpace before the corresponding class. If special circumstances require it, specific lecture recordings may be shared, but this is an exception, not a rule. If you need a lecture recording due to illness or other reasonable absence, let the instructor know.

<!-- \vskip6pt\noindent If/when classes are held in person, every class will be \textbf{simultaneously} streamed live on Zoom (at the address above), so that students can either attend remotely or physically in person. The stream \textbf{will be recorded} and uploaded. This is offered so that students who cannot physically attend \textbf{for any reason} have the option to attend class virtually without penalty. -->

\vskip6pt\noindent The class will progress according to a weekly schedule (provided below). Both lecture periods each week will consist of slides that cover related concepts, sometimes including live coding to demonstrate how to apply the concepts using the R language. Section each week will be dedicated to completing an R-based lab. The instructor will hold a minimum of 2 office hours weekly; TAs and ULAs will hold office hours as well, with specific details provided on the course GauchoSpace page.

<!-- \newpage -->
\subsection*{Required Materials}
\textsc{The books} and software used for this class are as follows. Note that all are freely available online and do not require purchase.

\begin{itemize}
    \item \textbf{Required for PSTAT 131 students}: \textit{An Introduction to Statistical Learning with Applications in R} (or ISLR), by G. James, D. Witten, T. Hastie, R. Tibshirani. Available: \href{https://www.statlearning.com/}{https://www.statlearning.com/}
    \item \textbf{Required for PSTAT 231 students}: \textit{The Elements of Statistical Learning: Data Mining, Inference, and Prediction} (or ESL), by T. Hastie, R. Tibshirani, J. Friedman. Available: \href{https://hastie.su.domains/ElemStatLearn/}{https://hastie.su.domains/ElemStatLearn/}
    \item \textbf{Required for all}:
    \begin{itemize}
        \item The R statistical environment version 4.1.2, available here: \href{https://www.r-project.org/}{https://www.r-project.org/}
        \item The RStudio IDE (integrated development environment) Desktop version. Available: \href{https://www.rstudio.com/products/rstudio/download/#download}{https://www.rstudio.com/} 
    \end{itemize}
\end{itemize}

\subsection*{Supplemental Materials}
\textsc{The following} are materials that are \textbf{not required} for this course, but are \textbf{recommended}. Don't feel expected to read all of these; I encourage you to use them as reference manuals and look subjects up as necessary.

\begin{itemize}
    \item \textit{R for Data Science}, by H. Wickham, G. Grolemund. Available: \href{https://r4ds.had.co.nz/index.html}{https://r4ds.had.co.nz/index.html}
    \item \textit{The StatQuest Illustrated Guide to Machine Learning}, by Josh Starmer. Available \href{https://www.amazon.com/dp/B0BLM4TLPY}{on Amazon}: \$27 for paperback. Based on videos available free at \href{https://www.youtube.com/@statquest}{https://www.youtube.com/@statquest}
    \item \textit{Supervised Machine Learning for Text Analysis in R}, by E. Hvitfeldt and J. Silge. Available: \href{https://smltar.com/}{https://smltar.com/}
    \item \textit{Feature Engineering and Selection}, by M. Kuhn and K. Johnson. Available: \href{http://www.feat.engineering/}{http://www.feat.engineering/}
\end{itemize}

<!-- \newpage -->
\subsection*{Assessments}
\textsc{Your attainment} of course learning outcomes will be measured by the following assessments, with the relative weighting indicated in parentheses. All assignments within each category are given equal weight.

\vskip6pt\noindent Collaboration and open science are fundamental aspects of data science. You can (and are encouraged) to use the Internet, StackOverflow, etc. as a resource when coding. However, you \textbf{should not} directly copy code or answers. Your code should be well documented; include comments describing each line. If you use a source for help coding, you \textbf{must} cite it. You \textbf{are permitted} to collaborate/work in groups on the homework if you choose, but everyone should work on their own final project -- it is not a group assignment.

\vskip6pt\noindent You will \textbf{not} be graded on your completion of lab work or your attendance of labs, but doing the labs will be greatly beneficial for your homework and final project grades. You are strongly encouraged to attend lab sections and follow along with the materials for each lab, which will be posted each week.

\begin{itemize}
\item \textbf{Homework} (50\%). Homework is assigned approximately every two weeks (this may vary) and will always be due by Sundays at 11:59 PM PDT. The graduate students will need to complete additional questions, but all assignments are ultimately rescaled to be out of 50 points. There are a total of \textbf{six} homework assignments. 

\item \textbf{Final Project} (50\%). The final project is a significant portion of the class and allows students to demonstrate their understanding of the material by working with a data set of their own choosing. Each student should begin thinking about their project and looking for a data set immediately; a page on GauchoSpace provides a list of possible resources. You'll receive a lot of guidance about the project over the course of the quarter.

\vskip6pt\noindent The project will require a large amount of work and cannot be satisfactorily completed in only a day (or even a week). You are \textbf{strongly advised} to work on it in stages throughout the quarter. See GauchoSpace for more detailed instructions, a rubric, and several examples of exemplary past projects.
\end{itemize}

\subsection*{Course Schedule}
\textsc{The weekly} schedule is indicated below. The topics and reading are subject to change based on the progress of the class.

\begin{table}[H]
\begin{tabular}{@{}llll@{}}
\toprule
                & \textbf{Topic}        & \textbf{Assignment}                                            & \textbf{Project Stage} \\ \midrule
\textbf{Week 1} & Intro to ML           & Data Memo                                                               & Pick topic             \\
\textbf{Week 2} & Linear models     & Homework 1 & Find data              \\
\textbf{Week 3} & Logistic models   & Homework 2                                                     & Tidy data              \\
\textbf{Week 4} & Discriminant analysis & Homework 3                                                     & EDA                    \\
\textbf{Week 5} & Resampling \& feature engineering &                                                   &                     \\
\textbf{Week 6} & Regularization        & Homework 4                                                     & Run models             \\
\textbf{Week 7} & Tree-based methods    & Homework 5                                                     &                        \\
\textbf{Week 8} & Clustering            &                                                      & Write-up               \\
\textbf{Week 9} & SVMs                  & Homework 6                                                               & Edits                  \\
\textbf{Week 10} & Neural networks       & Final Project                                                  & Final draft            \\ \bottomrule
\end{tabular}
\end{table}

\subsection*{Time Commitment}
\textsc{The course} is 4 credit units; each credit unit corresponds to an approximate time commitment of 3 hours. You should expect to allocate 12 hours per week to the course. If you find yourself spending considerably more time on the course on a regular basis, please let the instructor or TAs know so that we can help you balance the workload.

\noindent A suggested allocation of this time is as follows: 
\begin{itemize}
    \item Reading and class time: 3 hours (25\%)
    \item Homework: 4.5 hours (37.5\%)
    \item Sections: 1 hour (8.3\%)
    \item Final project: 4.5 hours (37.5\%)
\end{itemize}

<!-- %\newpage -->
\section*{Course Policies}

\subsection*{Communication}
\textsc{There are four} means of communication with other students or the instructional team: during/after class, office hours, email, and individual appointments. \textbf{Please use them in that order}. Note that I am notoriously slow at responding to email, which is why it is low on the list; to compensate, however, I offer several office hours weekly and am always willing to discuss problems or answer questions in person/during class.
\begin{enumerate}

    \item \textbf{During/after class}. The easiest guaranteed way to contact me is to come up after class and say hello, or to raise your hand and ask a question during class.
    
    \item \textbf{Office hours}. Office hours are offered at a minimum of twice weekly. I offer 4 office hours a week, and the other(s) are held by various combinations of TAs or ULAs. These are opportunities to interact informally, ask questions, and discuss course material or assignments.
    
    \item \textbf{Email}. Please use email with discernment for simple communication. A response is guaranteed within 48 weekday hours (so if you email on Friday afternoon, you may not receive a reply until Tuesday afternoon). If your message is time-sensitive, please indicate so in the subject, and I will do my best to respond promptly.

    \item \textbf{Appointment}. You can schedule individual 20-minute appointments with me as needed. These appointments may be either on Zoom or in person. This mode of communication is best suited to more complex or nuanced communication regarding personal matters. If you schedule an appointment, you will be prompted to indicate what you wish to discuss. 
\end{enumerate}

\subsection*{Extra Credit} 
\textsc{If the class} reaches a 90\% submission rate of ESCI surveys at the end of the quarter, the \textbf{entire class} will receive 2 free points on the final project.

<!-- %\newpage -->
\subsection*{Grades} 
\textsc{Your overall grade} in the course will be calculated as the weighted average of the proportions of total possible points in each assessment category according to the weightings indicated in the Assessments section and reported as a percentage rounded to two decimal places. Tentatively, letter grades will be assigned according to the rubric below -- a curve is possible, but not guaranteed.

\begin{center}
\begin{tabular}{lr}
    A+ &100\% \\
    A &93\% -- 99.99\%  \\
    A- &90\% -- 92.99\% \\
    B+ &87\% -- 89.99\% \\
    B &83\% -- 86.99\% \\
    B- &80\% -- 82.99\% \\
    C+ &77\% -- 79.99\% \\
    C &73\% -- 76.99\% \\
    C- &70\% -- 72.99\% \\
    D+ &67\% -- 69.99\% \\
    D &60\% -- 66.99\% \\
    F &0\% -- 59.99\%
\end{tabular}
\end{center}

\noindent \textsc{You can} keep track of your marks on individual assessments, your marks in each assessment category, and your overall grade in the GauchoSpace gradebook. Please notify the instructor or TAs of any errors in grade \textit{entry}; please do not attempt to negotiate the grades themselves. If at the end of the course you believe your grade was unfairly assigned, you are entitled to contest it according to the procedure outlined \href{https://my.sa.ucsb.edu/catalog/Current/AcademicPoliciesProcedures/ContestedGrades.aspx}{here} in the UCSB General Catalog.


\subsection*{Deadlines} 
\textsc{You receive} two free late homework submissions without penalty. This policy applies only to homeworks. When you wish to use one of these late submissions, simply submit within one week of the original deadline, and \textbf{add a note} at the beginning of the assignment explaining that it is a free late submission.

\vskip6pt\noindent \textsc{Non-exempted} homeworks submitted within one week of the deadline will be awarded 50\% credit. \textbf{No credit} will be awarded for homework turned in more than one week late; please plan ahead and submit your work on time.

\vskip6pt\noindent \textsc{The final project} deadline is firm and no late submissions will be accepted.

\subsection*{Extensions} 
\textsc{Extensions} may be granted based on individual circumstances at the instructor's discretion.

\subsection*{Conduct} 
\textsc{Please be mindful} of maintaining respectful and kind communication.  You are expected to uphold the UCSB student code of conduct in your behavior when in class, in section, or interacting with other students or the instructional team. You can find the student code of conduct on the Office of Student Conduct website from \href{http://studentconduct.sa.ucsb.edu/policies-procedures}{this page}. If you are uncomfortable with the conduct of another individual for any reason, please notify the instructor or TAs.

\subsection*{Academic Integrity} 
\textsc{Please maintain integrity} in learning. Your work in the course must be your own. Any form of plagiarism, cheating, misrepresentation of individual effort on assignments and assessments, falsification of information or documents, or misuse of course materials compromises your own learning experience, that of your peers, and undermines the integrity of the UCSB community. Any evidence of dishonest conduct will be discussed with the student(s) involved and reported to the Office of Student Conduct. Depending on the nature of the evidence and the violation, penalty in the course may range from loss of credit to automatic failure. For a definition and examples of dishonesty, a discussion of what constitutes an appropriate response from faculty, and an explanation of the reporting and investigation process, see the \href{https://studentconduct.sa.ucsb.edu/academic-integrity}{OSC page on academic integrity}. 

\subsection*{Accommodations} 
\textsc{Reasonable accommodations} will be made for any student with a qualifying disability. Such requests should be made through the Disabled Students Program (DSP). More information, instructions on how to access accommodations, and information on related resources can be found on \href{https://dsp.sa.ucsb.edu/}{DSP website}. Remote learning may present unique accommodation needs requiring additional flexibility; students receiving accommodation via DSP are invited to discuss this with the instructor if desired.

\subsection*{Student Evaluations} 
\textsc{Toward the end} of the term, you will be given an opportunity to provide feedback about the course. Your suggestions and assessments are essential to improving the course, so please take the time to fill out the evaluations thoughtfully. 

\subsection*{Student Resources}
\textsc{Any students} in need are encouraged to make use of the following resources.

\begin{itemize}
    \item Financial Crisis Response Team \\ 
    \href{https://food.ucsb.edu/about/committees/financial-crisis-response-team}{https://food.ucsb.edu/about/committees/financial-crisis-response-team}
    \item Food Security and Basic Needs (Food, Housing, Technology) Advising Center \\
    \href{https://food.ucsb.edu/resources/basic-needs-advocates}{https://food.ucsb.edu/resources/basic-needs-advocates}
    \item Undocumented Student Services \\
    \href{http://www.sa.ucsb.edu/dreamscholars/home}{http://www.sa.ucsb.edu/dreamscholars/home}
    \item Campus Advocacy, Resources, and Education (CARE) \\
    \href{https://care.ucsb.edu/}{https://care.ucsb.edu/} \\
    24/7 Confidential Phone: (805) 893-4613
    \item The Trevor Project \\  \href{https://www.thetrevorproject.org/}{https://www.thetrevorproject.org/}
    \item Counseling and Psychological Services (CAPS) \\ 
    \href{https://caps.sa.ucsb.edu/}{https://caps.sa.ucsb.edu/} \\
    24/7 Counselors: (805) 893-4411, press 2
\end{itemize}
